kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-etc-pihole-pv
  labels:
    directory: etc-pihole
spec:
  storageClassName: {{ .Release.Name }}-local-sc
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /etc/pihole
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.nodeHostname | quote }}

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-etc-dnsmasqd-pv
  labels:
    directory: etc-dnsmasq.d
spec:
  storageClassName: {{ .Release.Name }}-local-sc
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /etc/dnsmasq.d
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.nodeHostname | quote }}
