kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-etc-pihole-pvc
spec:
  storageClassName: {{ .Release.Name }}-local-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      directory: etc-pihole

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-etc-dnsmasqd-pvc
spec:
  storageClassName: {{ .Release.Name }}-local-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      directory: etc-dnsmasq.d